name:                Flint2
version:             0.1.0.0
github:              "monien/Flint2"
license:             BSD3
author:              "Hartmut Monien"
maintainer:        "hmonien@uni-bonn.de"
copyright:         "Copyright (c) 2022 Hartmut Monien"
category:           Math
synopsis:          "Haskell bindings for the flint library for number theory"

extra-source-files:
- README.md
- ChangeLog.md

description:  Please see the README on GitHub at <https://github.com/monien/Flint2#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  flint_test:
    source-dirs: app
    main: Main.hs
    dependencies: 
    - QuickCheck
    - Flint2
    extra-libraries: flint, gmp, mpfr
      
library:
  source-dirs: src 
  exposed-modules:
   - Data.Number.Flint
   - Data.Number.Flint.Flint
   - Data.Number.Flint.Fmpz
   - Data.Number.Flint.Fmpz.Arith
   - Data.Number.Flint.Fmpz.Factor
   - Data.Number.Flint.Fmpz.Mat
   - Data.Number.Flint.Fmpz.Vec
   - Data.Number.Flint.Fmpz.Poly
   - Data.Number.Flint.Fmpz.Poly.Factor
   - Data.Number.Flint.Fmpz.LLL
   - Data.Number.Flint.Fmpq
   - Data.Number.Flint.Fmpq.Vec
   - Data.Number.Flint.Fmpq.Poly
   - Data.Number.Flint.Flint.External
   - Data.Number.Flint.Flint.Internal
   - Data.Number.Flint.NMod
   - Data.Number.Flint.NMod.Mat
   - Data.Number.Flint.NMod.Poly
   - Data.Number.Flint.NMod.Poly.Factor
   - Data.Number.Flint.Support.D.Mat
   - Data.Number.Flint.Support.Mpf.Mat
  other-modules:
   - Data.Number.Flint.Flint.FFI
   - Data.Number.Flint.Flint.External.GMP.FFI 
   - Data.Number.Flint.Flint.External.Mpfr.FFI 
   - Data.Number.Flint.Flint.Internal.FFI 
   - Data.Number.Flint.Fmpz.FFI
   - Data.Number.Flint.Fmpz.Arith.FFI
   - Data.Number.Flint.Fmpz.Factor.FFI
   - Data.Number.Flint.Fmpz.Mat.FFI
   - Data.Number.Flint.Fmpz.Vec.FFI
   - Data.Number.Flint.Fmpz.Poly.FFI
   - Data.Number.Flint.Fmpz.Poly.Factor.FFI
   - Data.Number.Flint.Fmpz.LLL.FFI
   - Data.Number.Flint.Fmpq.FFI
   - Data.Number.Flint.Fmpq.Vec.FFI
   - Data.Number.Flint.Fmpq.Poly.FFI
   - Data.Number.Flint.NMod.FFI
   - Data.Number.Flint.NMod.Mat.Struct
   - Data.Number.Flint.NMod.Poly.Struct
   - Data.Number.Flint.NMod.Poly.Factor.Struct
   - Data.Number.Flint.Support.D.Mat.FFI
   - Data.Number.Flint.Support.Mpf.Mat.FFI
  c-sources:
    - csrc/fmpz/init.c
    - csrc/fmpz/clear.c
    - csrc/fmpz_factor/init.c
    - csrc/fmpz_factor/clear.c
    - csrc/fmpz_factor/fprint.c
    - csrc/fmpz_factor/get_str.c
    - csrc/fmpz_vec/get_str.c
    - csrc/fmpz_mat/get_str.c
    - csrc/fmpz_mat/get_str_pretty.c
    - csrc/fmpq_vec/get_str.c
  build-tools: hsc2hs
  extra-libraries: flint
  
tests:
  Flint2-test:
    main: Spec.hs
    source-dirs:  test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Flint2
