name:                Flint2
version:             0.1.0.0
github:              "monien/Flint2"
license:             BSD3
author:              "Hartmut Monien"
maintainer:          "hmonien@uni-bonn.de"
copyright:           "Copyright (c) 2019 Hartmut Monien"
category:          Math
synopsis:          "Haskell bindings for the flint library for number theory"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/monien/Flint2#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  flint_test:
    source-dirs: app
    main: Main.hs
    dependencies:
    - QuickCheck
    - Flint2
      
library:
  source-dirs: src
  build-tools: hsc2hs
  dependencies:
  - hgmp
  extra-libraries: flint
  
tests:
  Flint2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Flint2
